import os
import shutil

# Fully cleared — regenerated from scratch each run
FOLDERS_TO_CLEAR = [
    "data/clusters",
    "data/predicted_masks",
    "data/storm_tracks",
    "data/prediction",
    "data/metrics",
]

# Only sequence files deleted — scalers and encoders kept
LSTM_FILES_TO_CLEAR = [
    "data/lstm_dataset/X_sequences.npy",
    "data/lstm_dataset/y_labels.npy",
    "data/lstm_dataset/y_behavior.npy",
    "data/lstm_dataset/y_stage1_train.npy",
    "data/lstm_dataset/y_stage1_val.npy",
    "data/lstm_dataset/y_stage1_test.npy",
    "data/lstm_dataset/y_stage2_train.npy",
    "data/lstm_dataset/y_stage2_val.npy",
    "data/lstm_dataset/y_stage2_test.npy",
    "data/lstm_dataset/X_train.npy",
    "data/lstm_dataset/X_val.npy",
    "data/lstm_dataset/X_test.npy",
    "data/lstm_dataset/y_reg_train.npy",
    "data/lstm_dataset/y_reg_val.npy",
    "data/lstm_dataset/y_reg_test.npy",
    "data/lstm_dataset/y_cls_train.npy",
    "data/lstm_dataset/y_cls_val.npy",
    "data/lstm_dataset/y_cls_test.npy",
    "data/lstm_dataset/class_weights.npy",
    "data/lstm_dataset/bob_sequence_idx.npy",
]

# NEVER delete — needed for prediction without retraining
LSTM_FILES_TO_KEEP = [
    "data/lstm_dataset/scaler.save",
    "data/lstm_dataset/target_scaler.save",
    "data/lstm_dataset/behavior_encoder.save",
    "data/lstm_dataset/label_map.save",
    "data/lstm_dataset/feature_cols.npy",
    "data/lstm_dataset/target_cols.npy",
    "data/lstm_dataset/log_transform_cols.npy",
]

# Output folders cleared — regenerated by dashboards



def fast_clear_folder(folder):
    if not os.path.exists(folder):
        print(f"  Skipped (not found): {folder}")
        return
    deleted = 0
    with os.scandir(folder) as entries:
        for entry in entries:
            try:
                if entry.is_file() or entry.is_symlink():
                    os.unlink(entry.path)
                    deleted += 1
                elif entry.is_dir():
                    shutil.rmtree(entry.path)
                    deleted += 1
            except Exception as e:
                print(f"  Error: {entry.path} -> {e}")
    print(f"  Cleaned {folder} ({deleted} items)")


def clean_pipeline():
    print("Cleaning pipeline data...\n")

    print("Clearing data folders:")
    for folder in FOLDERS_TO_CLEAR:
        fast_clear_folder(folder)

    print("\nClearing lstm_dataset sequences (keeping scalers):")
    cleared = 0
    for filepath in LSTM_FILES_TO_CLEAR:
        if os.path.exists(filepath):
            os.remove(filepath)
            cleared += 1
    print(f"  Removed {cleared} sequence files")

    print("\nVerifying scalers are intact:")
    for filepath in LSTM_FILES_TO_KEEP:
        status = "OK" if os.path.exists(filepath) else "MISSING"
        print(f"  [{status}] {filepath}")



    print("\nReady for fresh pipeline run")
    print("Note: Models in models/ are preserved")
    print("      Scalers in data/lstm_dataset/ are preserved")
    print("      Raw NPZ files in data/raw_npz/ are preserved")


if __name__ == "__main__":
    clean_pipeline()